/**
 * Storage abstraction.
 *
 * `local` keeps artefacts on the server's disk (the Docker volume), and `s3` /
 * `s3_compatible` push them to object storage. The driver is chosen from the
 * environment, and a missing credential produces an explicit error rather than a
 * silent fallback that would lose a customer's data.
 */
import { mkdir, readFile, writeFile, stat } from 'node:fs/promises'
import path from 'node:path'
import { createHash, randomUUID } from 'node:crypto'
import { and, desc, eq, sql } from 'drizzle-orm'
import { getDb, storageObjects } from '../db'
import { env } from '../env'
import { createLogger } from '../observability/logger'

const log = createLogger({ component: 'storage' })

export type StorageDriver = 'local' | 's3' | 's3_compatible'

export class StorageError extends Error {
  constructor(message: string, readonly code: 'not_configured' | 'not_found' | 'write_failed') {
    super(message)
    this.name = 'StorageError'
  }
}

export function storageDriver(): StorageDriver {
  if (env.STORAGE_DRIVER === 's3' || env.STORAGE_DRIVER === 's3_compatible') return env.STORAGE_DRIVER
  return 'local'
}

export function storageStatus() {
  const driver = storageDriver()
  return {
    driver,
    bucket: env.STORAGE_BUCKET ?? null,
    region: env.STORAGE_REGION ?? null,
    endpoint: env.STORAGE_ENDPOINT ?? null,
    ready: driver === 'local' ? true : Boolean(env.STORAGE_BUCKET && env.STORAGE_KEY && env.STORAGE_SECRET),
    requiredCredentials: [
      { service: 'AWS S3 (or compatible)', credential: 'Access key id', envVar: 'STORAGE_KEY', where: 'IAM → users → security credentials' },
      { service: 'AWS S3 (or compatible)', credential: 'Secret access key', envVar: 'STORAGE_SECRET', where: 'IAM → users → security credentials' },
      { service: 'AWS S3 (or compatible)', credential: 'Bucket name', envVar: 'STORAGE_BUCKET', where: 'S3 console' },
    ],
    localPath: driver === 'local' ? path.resolve(env.STORAGE_LOCAL_DIR) : null,
  }
}

function localRoot(): string {
  return path.resolve(env.STORAGE_LOCAL_DIR)
}

/** Path traversal guard: keys are generated by AIBA, never by a request body. */
function safeKey(key: string): string {
  const clean = key.replace(/\\/g, '/').replace(/\.\.+/g, '').replace(/^\/+/, '')
  if (!clean || clean.includes('\0')) throw new StorageError('Invalid storage key.', 'write_failed')
  return clean
}

export type StoredObject = {
  id: string
  key: string
  sizeBytes: number
  checksumSha256: string
  contentType: string
  url: string | null
}

export async function putObject(input: {
  workspaceId: string
  key: string
  body: string | Buffer
  contentType?: string
  /** Public artefacts (like an exported landing page) get a readable URL. */
  isPublic?: boolean
  metadata?: Record<string, unknown>
}): Promise<StoredObject> {
  const db = await getDb()
  const driver = storageDriver()
  const key = safeKey(input.key)
  const buffer = typeof input.body === 'string' ? Buffer.from(input.body, 'utf8') : input.body
  const checksum = createHash('sha256').update(buffer).digest('hex')
  const contentType = input.contentType ?? 'application/octet-stream'

  let url: string | null = null

  if (driver === 'local') {
    const target = path.join(localRoot(), key)
    if (!target.startsWith(localRoot())) throw new StorageError('Refusing to write outside the storage directory.', 'write_failed')
    await mkdir(path.dirname(target), { recursive: true })
    await writeFile(target, buffer)
    url = `/api/storage/${encodeURIComponent(key)}`
  } else {
    if (!env.STORAGE_BUCKET || !env.STORAGE_KEY || !env.STORAGE_SECRET) {
      throw new StorageError(
        'Object storage is selected but STORAGE_BUCKET, STORAGE_KEY and STORAGE_SECRET are not all set. Nothing was written.',
        'not_configured',
      )
    }
    const { S3Client, PutObjectCommand } = await import('@aws-sdk/client-s3')
    const client = new S3Client({
      region: env.STORAGE_REGION ?? 'us-east-1',
      endpoint: env.STORAGE_ENDPOINT,
      forcePathStyle: env.STORAGE_DRIVER === 's3_compatible',
      credentials: { accessKeyId: env.STORAGE_KEY, secretAccessKey: env.STORAGE_SECRET },
    })
    await client.send(
      new PutObjectCommand({
        Bucket: env.STORAGE_BUCKET,
        Key: key,
        Body: buffer,
        ContentType: contentType,
        Metadata: { workspaceId: input.workspaceId, checksum },
      }),
    )
    url = env.STORAGE_ENDPOINT ? `${env.STORAGE_ENDPOINT.replace(/\/$/, '')}/${env.STORAGE_BUCKET}/${key}` : `s3://${env.STORAGE_BUCKET}/${key}`
  }

  const provider = driver === 'local' ? 'local' : 's3'
  const bucket = driver === 'local' ? 'local' : (env.STORAGE_BUCKET ?? 'aiba-assets')

  const existing = await db
    .select({ id: storageObjects.id })
    .from(storageObjects)
    .where(and(eq(storageObjects.provider, provider), eq(storageObjects.bucket, bucket), eq(storageObjects.key, key)))
    .limit(1)

  const values = {
    workspaceId: input.workspaceId,
    provider,
    bucket,
    key,
    contentType,
    sizeBytes: buffer.byteLength,
    checksumSha256: checksum,
    url,
    isPublic: input.isPublic ?? false,
    createdByAgent: (input.metadata?.createdByAgent as string | undefined) ?? null,
  }

  const rows = existing[0]
    ? await db.update(storageObjects).set(values).where(eq(storageObjects.id, existing[0].id)).returning()
    : await db.insert(storageObjects).values(values).returning()

  log.info('object stored', { key, driver, sizeBytes: buffer.byteLength })
  return {
    id: rows[0]!.id,
    key,
    sizeBytes: buffer.byteLength,
    checksumSha256: checksum,
    contentType,
    url,
  }
}

export async function getObject(workspaceId: string, key: string): Promise<{ body: Buffer; object: typeof storageObjects.$inferSelect }> {
  const db = await getDb()
  const driver = storageDriver()
  const cleanKey = safeKey(key)
  const rows = await db
    .select()
    .from(storageObjects)
    .where(and(eq(storageObjects.workspaceId, workspaceId), eq(storageObjects.key, cleanKey)))
    .limit(1)
  const object = rows[0]
  if (!object) throw new StorageError(`No stored object for key "${cleanKey}".`, 'not_found')

  if (driver === 'local') {
    const target = path.join(localRoot(), cleanKey)
    if (!target.startsWith(localRoot())) throw new StorageError('Refusing to read outside the storage directory.', 'not_found')
    try {
      await stat(target)
    } catch {
      throw new StorageError('The object is recorded but the file is missing from disk.', 'not_found')
    }
    return { body: await readFile(target), object }
  }

  if (!env.STORAGE_BUCKET || !env.STORAGE_KEY || !env.STORAGE_SECRET) {
    throw new StorageError('Object storage is selected but not fully configured.', 'not_configured')
  }
  const { S3Client, GetObjectCommand } = await import('@aws-sdk/client-s3')
  const client = new S3Client({
    region: env.STORAGE_REGION ?? 'us-east-1',
    endpoint: env.STORAGE_ENDPOINT,
    forcePathStyle: env.STORAGE_DRIVER === 's3_compatible',
    credentials: { accessKeyId: env.STORAGE_KEY, secretAccessKey: env.STORAGE_SECRET },
  })
  const result = await client.send(new GetObjectCommand({ Bucket: env.STORAGE_BUCKET, Key: cleanKey }))
  const chunks: Buffer[] = []
  for await (const chunk of result.Body as AsyncIterable<Uint8Array>) chunks.push(Buffer.from(chunk))
  return { body: Buffer.concat(chunks), object }
}

export async function listObjects(workspaceId: string, limit = 200) {
  const db = await getDb()
  return db
    .select()
    .from(storageObjects)
    .where(eq(storageObjects.workspaceId, workspaceId))
    .orderBy(desc(storageObjects.createdAt))
    .limit(Math.min(limit, 500))
}

export async function storageUsage(workspaceId: string): Promise<{ objects: number; bytes: number; driver: StorageDriver }> {
  const db = await getDb()
  const rows = await db
    .select({ count: sql<string>`count(*)::text`, bytes: sql<string>`coalesce(sum(${storageObjects.sizeBytes}), 0)::text` })
    .from(storageObjects)
    .where(eq(storageObjects.workspaceId, workspaceId))
  return { objects: Number(rows[0]?.count ?? 0), bytes: Number(rows[0]?.bytes ?? 0), driver: storageDriver() }
}

/** Stable, collision-free key for generated artefacts. */
export function buildKey(parts: { workspaceId: string; projectId?: string | null; type: string; name: string; extension?: string }): string {
  const slug = parts.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 60)
  const scope = parts.projectId ? `projects/${parts.projectId}` : 'workspace'
  const extension = parts.extension ?? 'md'
  return `${parts.workspaceId}/${scope}/${parts.type}/${slug || randomUUID().slice(0, 8)}.${extension}`
}
